site_name: Florian Kleiser 
theme:
    logo: assets/testlogo2.png
    name: material
    features:
        - navigation.indexes
    palette:
    - scheme: slate
      toggle:
            icon: material/weather-sunny
            name: Dark mode
      primary: black
      accent: black

    - scheme: default
      toggle:
            icon: material/weather-night
            name: Light mode
      primary: black 
      accent: black

plugins:
    - search
    - callouts

markdown_extensions:
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - attr_list
    # - pymdownx.emoji:
    #     emoji_generator: !!python/name:pymdownx.emoji.to_png
    #     emoji_index: !!python/name:material.extensions.emoji.twemoji
    - pymdownx.pathconverter:
        base_path: ''
        absolute: false
    - nl2br 

extra_css:
    - assets/css/extra.css