site_name: Florian Kleiser 
theme:
    name: material
    features:
        - navigation.indexes
    palette:
        scheme: slate 
        primary: black
        accent: deep-purple 

plugins:
    - search

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.pathconverter:
        base_path: ''
        absolute: false
