site_name: IAD Methods, Florian Kleiser
theme:
    logo: assets/testlogo2.png
    name: material
    features:
        - navigation.indexes
    palette:
    - scheme: slate
      toggle:
            icon: material/weather-sunny
            name: Dark mode
      primary: black
      accent: black

    - scheme: default
      toggle:
            icon: material/weather-night
            name: Light mode
      primary: black 
      accent: black

repo_name: flokleiser/IADMethods_Blog
repo_url: https://github.com/flokleiser/IADMethods_Blog

plugins:
    - search
    - callouts

markdown_extensions:
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - attr_list
    - md_in_html
    - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
    - pymdownx.pathconverter:
        base_path: ''
        absolute: false
    - nl2br 

extra_css:
    - assets/css/extra.css