site_name: Florian Kleiser 
theme:
    logo: assets/testlogo2.png
    name: material
    features:
        - navigation.indexes
    palette:
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: black
      accent: black

    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: black 
      accent: black

plugins:
    - search

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.pathconverter:
        base_path: ''
        absolute: false
